package com.axiom

import com.axiom.model.shared.dto.Patient
import java.time.LocalDate
import java.time.LocalDateTime

val patients = List(
			Patient(
				id = 1L,
				accountNumber = "1001",
				unitNumber = "U01",
				lastName = "Smith",
				firstName = "John",
				sex = "M",
				dob = Some(LocalDate.of(1985, 6, 15)),
				hcn = Some("HCN001"),
				admitDate = Some(LocalDateTime.of(2025, 7, 1, 10, 0)),
				floor = Some("2"),
				room = Some("202"),
				bed = Some("B"),
				mrp = Some("Dr. House"),
				admittingPhys = Some("Dr. Wilson"),
				family = Some("Yes"),
				famPriv = Some("No"),
				hosp = Some("GH"),
				flag = Some("None"),
				service = Some("Cardiology"),
				address1 = Some("123 Main St"),
				address2 = None,
				city = Some("Thunder Bay"),
				province = Some("ON"),
				postalCode = Some("P7B2R5"),
				homePhoneNumber = Some("807-111-2222"),
				workPhoneNumber = Some("807-333-4444"),
				ohip = Some("OH12345"),
				attending = Some("Dr. Strange"),
				collab1 = None,
				collab2 = None,
				auroraFile = None
			),
			Patient(
				id = 2L,
				accountNumber = "1002",
				unitNumber = "U02",
				lastName = "Doe",
				firstName = "Jane",
				sex = "F",
				dob = Some(LocalDate.of(1990, 3, 22)),
				hcn = Some("HCN002"),
				admitDate = Some(LocalDateTime.of(2025, 7, 5, 14, 30)),
				floor = Some("3"),
				room = Some("305"),
				bed = Some("A"),
				mrp = Some("Dr. Who"),
				admittingPhys = Some("Dr. Watson"),
				family = Some("No"),
				famPriv = Some("Yes"),
				hosp = Some("GH"),
				flag = Some("High Risk"),
				service = Some("Neurology"),
				address1 = Some("456 Elm St"),
				address2 = Some("Apt 2"),
				city = Some("Toronto"),
				province = Some("ON"),
				postalCode = Some("M5V2N8"),
				homePhoneNumber = Some("416-555-6666"),
				workPhoneNumber = None,
				ohip = Some("OH98765"),
				attending = Some("Dr. X"),
				collab1 = Some("Dr. Y"),
				collab2 = Some("Dr. Z"),
				auroraFile = None
			)
		)
